### ISSUE TITLE
Implement typography components

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/devbout#116]
## Tasks

* [x] Implement `DTitle` component
* [x] Implement `DText` component
* [x] Integrate typography components

## Reference

![image](https://user-images.githubusercontent.com/14854181/112729334-ded81180-8f2b-11eb-84e0-fd7d6b9d2d4e.png)
