### ISSUE TITLE
Implement footer component

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/devbout#118]
## Tasks

* [x] Implement dynamic year
* [x] Implement dynamic copyright holder
* [x] Implement optional attribution

## Reference

![image](https://user-images.githubusercontent.com/14854181/112748002-5a33d480-8fb9-11eb-8dc4-d6c89c8371b9.png)
