### ISSUE TITLE
Enhance accordion components

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/devbout#122]
## Tasks

* [x] Simplify accordion components
* [x] Animate accordion panels
* [x] Align project buttons right
