### ISSUE TITLE
Reorganize components and stories

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/devbout#124]
## Tasks

* [x] Group all accordion components into `accordion` directory
* [x] Group all button components into `button` directory
* [x] Group all card components into `card` directory
* [x] Group all dropdown components into `dropdown` directory
* [x] Group all typography components into `typography` directory
* [x] Group all other components into `misc` directory
* [x] Refactor Storybook to reflect components hierarchy
