### ISSUE TITLE
Implement API abstraction

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/devbout#53]
To achieve clean codebase and support multiple services, there needs to be abstraction over API.

## Tasks

* [x] Implement `devbout` plugin
* [x] Integrate the plugin into stores
* [x] Remove `@nuxtjs/axios` module
* [x] Unit test the plugin
