### ISSUE TITLE
Implement dynamic source icon

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/devbout#72]
## Tasks

* [ ] Set `mdi-github` icon if platform is GitHub
* [ ] Set `mdi-gitlab` icon if platform is GitLab
* [ ] Set `mdi-earth` for any other platform

## Reference

![image](https://user-images.githubusercontent.com/14854181/107262102-6fbc6180-6a40-11eb-8f07-3cb71c8d448c.png)
