### ISSUE TITLE
Implement DIcon component

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/devbout#93]
## Tasks

* [x] Integrate Font Awesome icons
* [x] Implement the component
* [x] Document with stories
